spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:tcp://localhost/~/cotato2
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
      format_sql: true
  logging.level:
    org.hibernate.SQL: debug